# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alex Puskaric — Developer Portfolio
email: puskaraxander@gmail.com
description: >-
  Portfolio of Alex Puskaric — showcasing software projects, resume, and contact information.
baseurl: "/AlexPuskaricDev" # leave blank if deploying to root domain
url: "https://xanderap25.github.io/AlexPuskaricDev/" # replace with your real domain (or GitHub Pages URL)
github_username: XanderAP25

# Build settings
theme: null
#remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# _config.yml
navigation_header:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Resume"
    url: "/assets/Resume%20as%20of%205_7_2025.pdf"
    html_options: { target: "_blank" }  
  - title: "About"
    url: "/about"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
